show databases;
use gmall;

select common from ods_log_inc;
select * from ods_activity_info_full;
select * from ods_activity_rule_full;
select * from ods_base_category1_full;
select * from ods_base_category2_full;
select * from ods_base_category3_full;
select * from ods_base_dic_full;
select * from ods_base_province_full;
select * from ods_base_region_full;
select * from ods_base_trademark_full;
select * from ods_cart_info_full;
select * from ods_coupon_info_full;
select * from ods_sku_attr_value_full;
select * from ods_sku_info_full;
select * from ods_sku_sale_attr_value_full;
select * from ods_spu_info_full;
select * from ods_cart_info_inc;
select * from ods_comment_info_inc;
select * from ods_coupon_use_inc;
select * from ods_favor_info_inc;
select * from ods_order_detail_inc;
select * from ods_order_detail_activity_inc;
select * from ods_order_detail_coupon_inc;
select * from ods_order_info_inc;
select * from ods_order_refund_info_inc;
select * from ods_order_status_log_inc;
select * from ods_payment_info_inc;
select * from ods_refund_payment_inc;
select * from ods_user_info_inc;